
log:
  level: INFO
  path: logs/

node:
  http:
    enabled: true
    as_server: true
    server_ip: 127.0.0.1
    server_port: 10702
  eth:
    enabled: false
    eth_ip: 127.0.0.1
    eth_port: 8545
    contract_addr: ''
  ipfs:
    enabled: false
    addr: /dns/10.72.100.12/tcp/5001/http

app:
  socket:
    bind_ip: 127.0.0.1
    bind_port: 10701
  http:
    enabled: true
    webui_enabled: false
    bind_ip: 0.0.0.0
    bind_port: 10700
    allow_cmd:
      - gfl_p
      - node
  shell:
    type: ipython
