version: 1

formatters:
  common:
    format: '%(asctime)s %(process)5d %(name)16s [%(levelname)-5s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: common
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: '{logs_root}/root.log'
    formatter: common
  error:
    class: logging.FileHandler
    level: ERROR
    filename: '{logs_root}/error.log'
    formatter: common
  core:
    class: logging.FileHandler
    level: INFO
    filename: '{logs_root}/core.log'
    formatter: common

loggers:
  gfl:
    level: INFO
    handlers: [file, error]
    propagate: no
  gfl.core:
    level: INFO
    handlers: [core]
    propagate: yes

root:
  level: INFO
  handlers: [file]